### ISSUE TITLE
Please add the remove label in the pr-extract-issues

### ISSUE THREAD

**Issue by BushiReddy3** [actions-cool/pr-extract-issues#20]

**Comment by xrkffgg** [comment]
will support

**Comment by BushiReddy3** [comment]
> will support

Please guide me, How to use it. 
Or need to implement?

**Comment by xrkffgg** [comment]
use `remove-labels`

**Comment by BushiReddy3** [comment]
Thank you for support and implementation. 
But I have found few issues. Raising another issue.
