### ISSUE TITLE
Bugs while extracting issues from pull request/  pr-extract-issues code.

### ISSUE THREAD

**Issue by BushiReddy3** [actions-cool/pr-extract-issues#22]
Hi 
I found few below issues. could you please check and implement. 

Note: I have used adding labels and remove labels at the same time. 

**Case 1:** 

if we use two bug/issue numbers in the pull request title/body, then its failing to remove the label on the second bug/issue number. 

**Case 2:**

while using remove label, if label is not available in that issue/bug number then its failing. 
Can we add if condition? if label is not available then can we ignore remove-label and **add-label** function should execute. 

**Case 3:**

If I comment with issue/bug number in the pull request (Not body, pull requests comments), It is not working. 
I think it is not implemented. 

Could you please implement above scenarios and fix the bugs?

**Comment by xrkffgg** [comment]
case 1: please provide how do you define?

case 2: can fix

case 3: will support

**Comment by BushiReddy3** [comment]
Thanks for quick response. 

Case 1: 
I defined in the pull request title like **"issues #123 #456"**  

So, issue 123 is executing successfully, but it is failing to execute second one. Its getting error like "label does not exists"

Reproduce steps:

1. Create a two issues with the labels "L1" and "L2" (for example issue number #123 and #456)
2. Create a pull request with the title "Issues fixing #123 #456"
3. use the parameters 
     "issues-label (Add-lables) is **"ready-for-testing"**  
      "remove-label   is  **"L1"**"
4. Then execute the GitHub action.

**Comment by BushiReddy3** [comment]
Hi 
Any update on this? 

And also, I found that like "if pull request merging with master branch, in that "commit" section getting pull request number also. in that case also it is failing. 

I think, if label is does not exit then can we ignore?

**Comment by xrkffgg** [comment]
> I think, if label is does not exit then can we ignore?

yes

**Comment by BushiReddy3** [comment]
I guess, if we ignore that like "If label does not exit" then case 1 and case 2 will be resolve with that change. 
only Case 3 need to be implement.

**Comment by xrkffgg** [comment]
> If label does not exit

has fixed.

> about comment

I don't think it's necessary, if you are the auth or repository maintainer of this PR, you can just edit the PR without commenting.
